name: Insomnia
main: com.etherelements.hereinplainsight.insomnia.insomnia
version: 0.2
commands:
  insomnia:
    description: Not yet implemented.  Not sure it's necessary, why did you type it?
    usage: /<command>
    permission-message: You don't have permission to do that.